[project]
name = 'Time-Dilated-Smart-Contract-Execution'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.gravity-well-computation]
path = 'contracts/gravity-well-computation.clar'
clarity_version = 2
epoch = 2.5

[contracts.relativistic-time-tracking]
path = 'contracts/relativistic-time-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.time-dilation-arbitrage]
path = 'contracts/time-dilation-arbitrage.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
